### ISSUE TITLE
Flashing button spells

### ISSUE THREAD

**Issue by jeff1326** [bhhandley/CleveRoidMacros#7]
When using this package, i see a square flashing 

![image](https://github.com/user-attachments/assets/4fd21ab2-f9dd-445b-af51-6dd3444ad43f)

This only appear if i activate `Turtle Dragon Flight` addon

**Comment by bhhandley** [comment]
Thanks for reporting -- a couple others had tagged me about the issue on Discord already.  Oddly it doesn't happen with default bars, pfUI, Bongos or ShaguTweaks (default bars and what tDF uses) so I never bothered testing.  In any case, it's already fixed in the next version.  Unfortunately I had to go out of town so the release is going to be delayed a few days.

**Comment by jeff1326** [comment]
Thank you, I'll give it a try when it will be available 🙂

**Comment by RemulusLaxx** [comment]
Hi - Unsure if you've pushed an update since above. Just as an FYI, I'm still experiencing above issue.
I've tried;
Latest versions of both addons.
"dev" version of Cleveroid.
Removing all macros.
Manually re-installing both addons.

As you say, it only affects the additional "left" "right" action bars, not the primary bar.
I personally only noticed after the official merge of RoidMacros and CleverMacros. Perhaps, 6-8 weeks ago, the issue wasn't present.

Thanks for all you do :)

**Comment by RemulusLaxx** [comment]
Temporary resolution. Remove "tActionBars.lua" file from the main Turtle Dragonflight directory.
TWow>Interface>Addons>Tdf>tActionBars.lua.

I found this has resolved it, for the time being, if it's of any use.
